-- Ithaca reusable real-estate demo platform
-- Phase 1: database-enforced demo workspace isolation.
--
-- This is a forward-only, non-destructive migration. Existing Hilltop records
-- are assigned to one public/default "Hilltop Template" workspace. Workspaces
-- are archived rather than deleted and every workspace foreign key is RESTRICT.

begin;

create extension if not exists "pgcrypto";
create schema if not exists private;
revoke all on schema private from public;

create table if not exists public.demo_workspaces (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null,
  status text not null default 'active',
  is_public_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint demo_workspaces_name_valid
    check (name = btrim(name) and char_length(name) between 2 and 120),
  constraint demo_workspaces_slug_valid
    check (slug = lower(slug) and slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' and char_length(slug) <= 80),
  constraint demo_workspaces_status_valid
    check (status in ('active', 'archived')),
  constraint demo_workspaces_slug_key unique (slug)
);

create unique index if not exists demo_workspaces_one_public_default_idx
  on public.demo_workspaces (is_public_default)
  where is_public_default = true;

create index if not exists demo_workspaces_active_name_idx
  on public.demo_workspaces (name)
  where status = 'active';
create index if not exists demo_workspaces_created_by_idx
  on public.demo_workspaces (created_by);

drop trigger if exists trg_demo_workspaces_set_updated_at on public.demo_workspaces;
create trigger trg_demo_workspaces_set_updated_at
before update on public.demo_workspaces
for each row execute function public.set_updated_at();

create table if not exists public.demo_workspace_memberships (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.demo_workspaces(id) on delete restrict,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'agent',
  status text not null default 'active',
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint demo_workspace_memberships_role_valid
    check (role in ('super_admin', 'branch_manager', 'agent')),
  constraint demo_workspace_memberships_status_valid
    check (status in ('active', 'revoked')),
  constraint demo_workspace_memberships_workspace_user_key
    unique (workspace_id, auth_user_id)
);

create index if not exists demo_workspace_memberships_auth_user_idx
  on public.demo_workspace_memberships (auth_user_id, status);
create index if not exists demo_workspace_memberships_workspace_idx
  on public.demo_workspace_memberships (workspace_id, status);
create index if not exists demo_workspace_memberships_created_by_idx
  on public.demo_workspace_memberships (created_by);
create unique index if not exists demo_workspace_memberships_one_current_idx
  on public.demo_workspace_memberships (auth_user_id)
  where is_current = true;

drop trigger if exists trg_demo_workspace_memberships_set_updated_at on public.demo_workspace_memberships;
create trigger trg_demo_workspace_memberships_set_updated_at
before update on public.demo_workspace_memberships
for each row execute function public.set_updated_at();

-- Insert exactly one safe home for all pre-workspace Hilltop data. The UUID is
-- generated by Postgres and is never hard-coded in application code.
insert into public.demo_workspaces (name, slug, status, is_public_default)
values ('Hilltop Template', 'hilltop-template', 'active', true)
on conflict (slug) do update
set name = excluded.name,
    status = 'active',
    is_public_default = true;

-- Add/backfill workspace_id only on company-owned data. Geographic reference
-- tables (provinces, cities, suburbs and location_search) intentionally remain
-- global and are not included here.
do $$
declare
  table_name text;
  default_workspace_id uuid;
  company_tables constant text[] := array[
    'branches',
    'staff_users',
    'properties',
    'property_images',
    'property_documents',
    'leads',
    'activity_logs',
    'lead_communication_logs',
    'app_settings',
    'cms_homepage_content',
    'cms_banners',
    'cms_team_profiles',
    'cms_testimonials',
    'cms_featured_properties',
    'cms_service_showcase_items',
    'cms_services_section',
    'cms_service_cards',
    'team_members',
    'market_price_statistics'
  ];
begin
  select id into strict default_workspace_id
  from public.demo_workspaces
  where is_public_default = true;

  foreach table_name in array company_tables loop
    if to_regclass(format('public.%I', table_name)) is not null then
      execute format('alter table public.%I add column if not exists workspace_id uuid', table_name);
      execute format('update public.%I set workspace_id = $1 where workspace_id is null', table_name)
        using default_workspace_id;
      execute format('alter table public.%I alter column workspace_id set not null', table_name);

      if not exists (
        select 1
        from pg_constraint
        where conrelid = format('public.%I', table_name)::regclass
          and conname = table_name || '_workspace_id_fkey'
      ) then
        execute format(
          'alter table public.%I add constraint %I foreign key (workspace_id) references public.demo_workspaces(id) on delete restrict',
          table_name,
          table_name || '_workspace_id_fkey'
        );
      end if;

      execute format(
        'create index if not exists %I on public.%I (workspace_id)',
        'idx_' || table_name || '_workspace_id',
        table_name
      );

      if not exists (
        select 1
        from pg_constraint
        where conrelid = format('public.%I', table_name)::regclass
          and conname = table_name || '_id_workspace_key'
      ) then
        execute format(
          'alter table public.%I add constraint %I unique (id, workspace_id)',
          table_name,
          table_name || '_id_workspace_key'
        );
      end if;
    end if;
  end loop;
end;
$$;

-- Replace formerly global business identifiers with workspace-local keys.
alter table if exists public.branches drop constraint if exists branches_name_key;
alter table if exists public.staff_users drop constraint if exists staff_users_email_key;
alter table if exists public.staff_users drop constraint if exists staff_users_auth_user_id_key;
alter table if exists public.properties drop constraint if exists properties_reference_number_key;
alter table if exists public.app_settings drop constraint if exists app_settings_setting_key_key;
alter table if exists public.cms_services_section drop constraint if exists cms_services_section_section_key_key;
alter table if exists public.cms_service_cards drop constraint if exists cms_service_cards_slug_key;
alter table if exists public.market_price_statistics drop constraint if exists market_price_statistics_market_year_key;

do $$
begin
  if to_regclass('public.branches') is not null and not exists (
    select 1 from pg_constraint where conrelid = 'public.branches'::regclass and conname = 'branches_workspace_name_key'
  ) then
    alter table public.branches add constraint branches_workspace_name_key unique (workspace_id, name);
  end if;
  if to_regclass('public.staff_users') is not null and not exists (
    select 1 from pg_constraint where conrelid = 'public.staff_users'::regclass and conname = 'staff_users_workspace_email_key'
  ) then
    alter table public.staff_users add constraint staff_users_workspace_email_key unique (workspace_id, email);
  end if;
  if to_regclass('public.staff_users') is not null and not exists (
    select 1 from pg_constraint where conrelid = 'public.staff_users'::regclass and conname = 'staff_users_workspace_auth_user_key'
  ) then
    alter table public.staff_users add constraint staff_users_workspace_auth_user_key unique (workspace_id, auth_user_id);
  end if;
  if to_regclass('public.properties') is not null and not exists (
    select 1 from pg_constraint where conrelid = 'public.properties'::regclass and conname = 'properties_workspace_reference_key'
  ) then
    alter table public.properties add constraint properties_workspace_reference_key unique (workspace_id, reference_number);
  end if;
  if to_regclass('public.app_settings') is not null and not exists (
    select 1 from pg_constraint where conrelid = 'public.app_settings'::regclass and conname = 'app_settings_workspace_setting_key'
  ) then
    alter table public.app_settings add constraint app_settings_workspace_setting_key unique (workspace_id, setting_key);
  end if;
  if to_regclass('public.cms_services_section') is not null and not exists (
    select 1 from pg_constraint where conrelid = 'public.cms_services_section'::regclass and conname = 'cms_services_section_workspace_key'
  ) then
    alter table public.cms_services_section add constraint cms_services_section_workspace_key unique (workspace_id, section_key);
  end if;
  if to_regclass('public.cms_service_cards') is not null and not exists (
    select 1 from pg_constraint where conrelid = 'public.cms_service_cards'::regclass and conname = 'cms_service_cards_workspace_slug_key'
  ) then
    alter table public.cms_service_cards add constraint cms_service_cards_workspace_slug_key unique (workspace_id, slug);
  end if;
  if to_regclass('public.market_price_statistics') is not null and not exists (
    select 1 from pg_constraint where conrelid = 'public.market_price_statistics'::regclass and conname = 'market_price_statistics_workspace_market_year_key'
  ) then
    alter table public.market_price_statistics
      add constraint market_price_statistics_workspace_market_year_key unique (
        workspace_id, area_key, property_type, purpose, currency_code, bedroom_bucket, year
      );
  end if;
end;
$$;

-- Cross-workspace references are rejected even if a caller knows another
-- tenant's UUID. Existing single-column FKs remain in place so their original
-- delete behaviour is preserved; these composite FKs add tenant consistency.
do $$
declare
  relation record;
  delete_clause text;
begin
  for relation in
    select * from (values
      ('staff_users','branch_id','branches','set null'),
      ('properties','branch_id','branches','restrict'),
      ('properties','assigned_agent_id','staff_users','set null'),
      ('property_images','property_id','properties','cascade'),
      ('property_documents','property_id','properties','cascade'),
      ('leads','property_id','properties','set null'),
      ('leads','branch_id','branches','restrict'),
      ('leads','assigned_agent_id','staff_users','set null'),
      ('activity_logs','branch_id','branches','set null'),
      ('activity_logs','property_id','properties','set null'),
      ('activity_logs','lead_id','leads','set null'),
      ('activity_logs','staff_user_id','staff_users','set null'),
      ('lead_communication_logs','lead_id','leads','cascade'),
      ('lead_communication_logs','staff_user_id','staff_users','set null'),
      ('app_settings','updated_by','staff_users','set null'),
      ('cms_homepage_content','updated_by','staff_users','set null'),
      ('cms_banners','updated_by','staff_users','set null'),
      ('cms_team_profiles','staff_user_id','staff_users','set null'),
      ('cms_team_profiles','updated_by','staff_users','set null'),
      ('cms_testimonials','updated_by','staff_users','set null'),
      ('cms_featured_properties','property_id','properties','cascade'),
      ('cms_featured_properties','updated_by','staff_users','set null'),
      ('cms_services_section','updated_by','staff_users','set null'),
      ('cms_service_cards','section_id','cms_services_section','restrict'),
      ('cms_service_cards','updated_by','staff_users','set null')
    ) as x(child_table, child_column, parent_table, delete_action)
  loop
    if to_regclass(format('public.%I', relation.child_table)) is not null
       and to_regclass(format('public.%I', relation.parent_table)) is not null
       and not exists (
         select 1 from pg_constraint
         where conrelid = format('public.%I', relation.child_table)::regclass
           and conname = relation.child_table || '_' || relation.child_column || '_workspace_fkey'
       ) then
      delete_clause := case
        when relation.delete_action = 'set null'
          then format('set null (%I)', relation.child_column)
        else relation.delete_action
      end;
      execute format(
        'alter table public.%I add constraint %I foreign key (%I, workspace_id) references public.%I(id, workspace_id) on delete %s',
        relation.child_table,
        relation.child_table || '_' || relation.child_column || '_workspace_fkey',
        relation.child_column,
        relation.parent_table,
        delete_clause
      );
    end if;
  end loop;
end;
$$;

-- Migrate every existing authenticated Hilltop staff identity into the
-- template workspace without changing or deleting the staff row.
insert into public.demo_workspace_memberships (
  workspace_id,
  auth_user_id,
  role,
  status,
  is_current,
  created_by
)
select
  su.workspace_id,
  su.auth_user_id,
  su.role,
  case when su.is_active then 'active' else 'revoked' end,
  su.is_active,
  su.auth_user_id
from public.staff_users su
where su.auth_user_id is not null
on conflict (workspace_id, auth_user_id) do update
set role = excluded.role,
    status = excluded.status,
    is_current = case
      when public.demo_workspace_memberships.is_current then true
      when excluded.status = 'active' and not exists (
        select 1 from public.demo_workspace_memberships current_membership
        where current_membership.auth_user_id = excluded.auth_user_id
          and current_membership.is_current = true
      ) then true
      else false
    end;

-- Private helpers are callable from policies/triggers but cannot be reached as
-- Data API RPC endpoints because the private schema is not exposed.
create or replace function private.current_demo_workspace_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select membership.workspace_id
  from public.demo_workspace_memberships membership
  join public.demo_workspaces workspace on workspace.id = membership.workspace_id
  where membership.auth_user_id = (select auth.uid())
    and membership.status = 'active'
    and membership.is_current = true
    and workspace.status = 'active'
  limit 1;
$$;

create or replace function private.default_demo_workspace_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select id
  from public.demo_workspaces
  where is_public_default = true
    and status = 'active'
  limit 1;
$$;

create or replace function private.is_current_workspace_super_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.demo_workspace_memberships membership
    join public.demo_workspaces workspace on workspace.id = membership.workspace_id
    where membership.auth_user_id = (select auth.uid())
      and membership.status = 'active'
      and membership.is_current = true
      and membership.role = 'super_admin'
      and workspace.status = 'active'
  );
$$;

create or replace function private.request_demo_workspace_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select case
    when (select auth.uid()) is null then private.default_demo_workspace_id()
    else private.current_demo_workspace_id()
  end;
$$;

revoke all on all functions in schema private from public;
grant usage on schema private to anon, authenticated;
grant execute on function private.current_demo_workspace_id() to authenticated;
grant execute on function private.default_demo_workspace_id() to anon, authenticated;
grant execute on function private.is_current_workspace_super_admin() to authenticated;
grant execute on function private.request_demo_workspace_id() to anon, authenticated;

-- A database trigger supplies workspace context for every insert. The browser
-- also sends workspace_id explicitly, but RLS/this trigger remain authoritative.
create or replace function private.assign_demo_workspace_id()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.workspace_id is null then
    new.workspace_id := private.request_demo_workspace_id();
  end if;

  if new.workspace_id is null then
    raise exception using
      errcode = '42501',
      message = 'No active demo workspace is available for this request.';
  end if;

  return new;
end;
$$;
revoke all on function private.assign_demo_workspace_id() from public;

do $$
declare
  table_name text;
  company_tables constant text[] := array[
    'branches','staff_users','properties','property_images','property_documents',
    'leads','activity_logs','lead_communication_logs','app_settings',
    'cms_homepage_content','cms_banners','cms_team_profiles','cms_testimonials',
    'cms_featured_properties','cms_service_showcase_items','cms_services_section',
    'cms_service_cards','team_members','market_price_statistics'
  ];
begin
  foreach table_name in array company_tables loop
    if to_regclass(format('public.%I', table_name)) is not null then
      execute format('drop trigger if exists %I on public.%I', 'trg_' || table_name || '_assign_workspace', table_name);
      execute format(
        'create trigger %I before insert on public.%I for each row execute function private.assign_demo_workspace_id()',
        'trg_' || table_name || '_assign_workspace',
        table_name
      );
    end if;
  end loop;
end;
$$;

-- Keep the pre-existing authorization helpers, now resolved against the
-- current membership/workspace rather than any staff row in any workspace.
create or replace function public.current_staff_user_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select su.id
  from public.staff_users su
  where su.auth_user_id = (select auth.uid())
    and su.workspace_id = private.current_demo_workspace_id()
    and su.is_active = true
  limit 1;
$$;

create or replace function public.is_active_super_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.is_current_workspace_super_admin();
$$;

revoke all on function public.current_staff_user_id() from public;
revoke all on function public.is_active_super_admin() from public;
grant execute on function public.current_staff_user_id() to authenticated;
grant execute on function public.is_active_super_admin() to authenticated;

-- Existing role-sensitive property triggers must resolve the staff profile in
-- the current workspace. Membership role is the fallback for a newly-created
-- workspace that does not yet contain an operational staff profile.
create or replace function public.enforce_property_classification_management()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  staff_role text;
  staff_branch_id uuid;
begin
  if (select auth.uid()) is null then return new; end if;

  select coalesce(su.role, membership.role), su.branch_id
    into staff_role, staff_branch_id
  from public.demo_workspace_memberships membership
  left join public.staff_users su
    on su.workspace_id = membership.workspace_id
   and su.auth_user_id = membership.auth_user_id
   and su.is_active = true
  where membership.auth_user_id = (select auth.uid())
    and membership.workspace_id = new.workspace_id
    and membership.status = 'active'
    and membership.is_current = true
  limit 1;

  if staff_role is null or staff_role not in ('super_admin', 'branch_manager') then
    raise exception using errcode = '42501', message = 'Only active super administrators and branch managers may manage property classification.';
  end if;
  if staff_role = 'branch_manager' and (
    staff_branch_id is null or new.branch_id is distinct from staff_branch_id
    or (tg_op = 'UPDATE' and old.branch_id is distinct from staff_branch_id)
  ) then
    raise exception using errcode = '42501', message = 'Branch managers may manage properties only within their assigned branch.';
  end if;
  return new;
end;
$$;

create or replace function public.enforce_property_currency_management()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  staff_role text;
  staff_branch_id uuid;
begin
  if (select auth.uid()) is null then return new; end if;

  select coalesce(su.role, membership.role), su.branch_id
    into staff_role, staff_branch_id
  from public.demo_workspace_memberships membership
  left join public.staff_users su
    on su.workspace_id = membership.workspace_id
   and su.auth_user_id = membership.auth_user_id
   and su.is_active = true
  where membership.auth_user_id = (select auth.uid())
    and membership.workspace_id = new.workspace_id
    and membership.status = 'active'
    and membership.is_current = true
  limit 1;

  if staff_role is null or staff_role not in ('super_admin', 'branch_manager') then
    raise exception using errcode = '42501', message = 'Only active super administrators and branch managers may manage property currency.';
  end if;
  if staff_role = 'branch_manager' and (
    staff_branch_id is null or new.branch_id is distinct from staff_branch_id
    or (tg_op = 'UPDATE' and old.branch_id is distinct from staff_branch_id)
  ) then
    raise exception using errcode = '42501', message = 'Branch managers may manage property currency only within their assigned branch.';
  end if;
  return new;
end;
$$;

-- Keep workspace membership synchronized when an Auth identity is linked to a
-- staff record. This preserves the existing manual Auth-user linking workflow.
create or replace function private.sync_staff_workspace_membership()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE'
     and old.auth_user_id is not null
     and (
       old.auth_user_id is distinct from new.auth_user_id
       or old.workspace_id is distinct from new.workspace_id
     ) then
    update public.demo_workspace_memberships
    set status = 'revoked', is_current = false, updated_at = now()
    where workspace_id = old.workspace_id
      and auth_user_id = old.auth_user_id;
  end if;

  if new.auth_user_id is null then
    return new;
  end if;

  insert into public.demo_workspace_memberships (
    workspace_id, auth_user_id, role, status, is_current, created_by
  ) values (
    new.workspace_id,
    new.auth_user_id,
    new.role,
    case when new.is_active then 'active' else 'revoked' end,
    new.is_active and not exists (
      select 1 from public.demo_workspace_memberships m
      where m.auth_user_id = new.auth_user_id and m.is_current = true
    ),
    (select auth.uid())
  )
  on conflict (workspace_id, auth_user_id) do update
  set role = excluded.role,
      status = excluded.status,
      is_current = case when excluded.status = 'revoked' then false else public.demo_workspace_memberships.is_current end,
      updated_at = now();

  return new;
end;
$$;
revoke all on function private.sync_staff_workspace_membership() from public;

drop trigger if exists trg_staff_users_sync_workspace_membership on public.staff_users;
create trigger trg_staff_users_sync_workspace_membership
after insert or update of auth_user_id, role, is_active, workspace_id on public.staff_users
for each row execute function private.sync_staff_workspace_membership();

-- Atomic, authenticated workspace lifecycle functions. There is deliberately
-- no delete function.
create or replace function public.switch_demo_workspace(p_workspace_id uuid)
returns public.demo_workspaces
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_id uuid := (select auth.uid());
  selected_workspace public.demo_workspaces;
begin
  if caller_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  select workspace.* into selected_workspace
  from public.demo_workspaces workspace
  join public.demo_workspace_memberships membership on membership.workspace_id = workspace.id
  where workspace.id = p_workspace_id
    and workspace.status = 'active'
    and membership.auth_user_id = caller_id
    and membership.status = 'active';

  if selected_workspace.id is null then
    raise exception using errcode = '42501', message = 'The requested workspace is unavailable.';
  end if;

  update public.demo_workspace_memberships
  set is_current = false, updated_at = now()
  where auth_user_id = caller_id and is_current = true;

  update public.demo_workspace_memberships
  set is_current = true, updated_at = now()
  where auth_user_id = caller_id and workspace_id = p_workspace_id and status = 'active';

  return selected_workspace;
end;
$$;

create or replace function public.create_demo_workspace(
  p_name text,
  p_slug text
)
returns public.demo_workspaces
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_id uuid := (select auth.uid());
  clean_name text := btrim(p_name);
  clean_slug text := lower(btrim(p_slug));
  created_workspace public.demo_workspaces;
begin
  if caller_id is null or not private.is_current_workspace_super_admin() then
    raise exception using errcode = '42501', message = 'Only an active super administrator can create a workspace.';
  end if;
  if clean_name is null or char_length(clean_name) not between 2 and 120 then
    raise exception using errcode = '22023', message = 'Workspace name must contain 2 to 120 characters.';
  end if;
  if clean_slug is null or clean_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' or char_length(clean_slug) > 80 then
    raise exception using errcode = '22023', message = 'Workspace slug must use lowercase letters, numbers, and single hyphens.';
  end if;
  begin
    insert into public.demo_workspaces (name, slug, status, created_by)
    values (clean_name, clean_slug, 'active', caller_id)
    returning * into created_workspace;
  exception when unique_violation then
    raise exception using errcode = '23505', message = 'A workspace with this slug already exists.';
  end;

  insert into public.demo_workspace_memberships (
    workspace_id, auth_user_id, role, status, is_current, created_by
  ) values (
    created_workspace.id, caller_id, 'super_admin', 'active', false, caller_id
  );

  perform public.switch_demo_workspace(created_workspace.id);

  return created_workspace;
end;
$$;

create or replace function public.archive_demo_workspace(p_workspace_id uuid)
returns public.demo_workspaces
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_id uuid := (select auth.uid());
  archived_workspace public.demo_workspaces;
  fallback_workspace_id uuid;
  was_current boolean;
begin
  if caller_id is null then
    raise exception using errcode = '42501', message = 'Authentication is required.';
  end if;

  select workspace.*
    into archived_workspace
  from public.demo_workspaces workspace
  join public.demo_workspace_memberships membership on membership.workspace_id = workspace.id
  where workspace.id = p_workspace_id
    and membership.auth_user_id = caller_id
    and membership.status = 'active'
    and membership.role = 'super_admin';

  select membership.is_current
    into was_current
  from public.demo_workspace_memberships membership
  where membership.workspace_id = p_workspace_id
    and membership.auth_user_id = caller_id
    and membership.status = 'active';

  if archived_workspace.id is null then
    raise exception using errcode = '42501', message = 'Only a workspace super administrator can archive this workspace.';
  end if;
  if archived_workspace.is_public_default then
    raise exception using errcode = '23514', message = 'The public default workspace cannot be archived.';
  end if;

  if was_current then
    select membership.workspace_id into fallback_workspace_id
    from public.demo_workspace_memberships membership
    join public.demo_workspaces workspace on workspace.id = membership.workspace_id
    where membership.auth_user_id = caller_id
      and membership.status = 'active'
      and membership.workspace_id <> p_workspace_id
      and workspace.status = 'active'
    order by workspace.created_at
    limit 1;

    if fallback_workspace_id is null then
      raise exception using errcode = '23514', message = 'Switch to or create another active workspace before archiving this one.';
    end if;
  end if;

  update public.demo_workspaces
  set status = 'archived', updated_at = now()
  where id = p_workspace_id
  returning * into archived_workspace;

  -- Invalidate the archived selection for every member. The auth guard can
  -- then atomically recover each user to their own remaining active workspace
  -- on the next request; no stale current marker points at archived data.
  update public.demo_workspace_memberships
  set is_current = false, updated_at = now()
  where workspace_id = p_workspace_id
    and is_current = true;

  if was_current then
    update public.demo_workspace_memberships
    set is_current = true, updated_at = now()
    where auth_user_id = caller_id and workspace_id = fallback_workspace_id;
  end if;

  return archived_workspace;
end;
$$;

revoke all on function public.switch_demo_workspace(uuid) from public;
revoke all on function public.create_demo_workspace(text, text) from public;
revoke all on function public.archive_demo_workspace(uuid) from public;
grant execute on function public.switch_demo_workspace(uuid) to authenticated;
grant execute on function public.create_demo_workspace(text, text) to authenticated;
grant execute on function public.archive_demo_workspace(uuid) to authenticated;

-- Workspace and membership tables expose only the caller's authorized list.
alter table public.demo_workspaces enable row level security;
alter table public.demo_workspace_memberships enable row level security;

drop policy if exists demo_workspaces_member_select on public.demo_workspaces;
create policy demo_workspaces_member_select
on public.demo_workspaces for select to authenticated
using (
  exists (
    select 1 from public.demo_workspace_memberships membership
    where membership.workspace_id = demo_workspaces.id
      and membership.auth_user_id = (select auth.uid())
      and membership.status = 'active'
  )
);

drop policy if exists demo_workspace_memberships_self_select on public.demo_workspace_memberships;
create policy demo_workspace_memberships_self_select
on public.demo_workspace_memberships for select to authenticated
using (auth_user_id = (select auth.uid()));

revoke all on public.demo_workspaces from anon, authenticated;
revoke all on public.demo_workspace_memberships from anon, authenticated;
grant select on public.demo_workspaces to authenticated;
grant select on public.demo_workspace_memberships to authenticated;

-- Remove every legacy policy from tenant-owned tables before installing the
-- current-workspace policies. Leaving one permissive legacy policy would OR
-- with the new policy and defeat isolation.
do $$
declare
  policy_record record;
  company_tables constant text[] := array[
    'branches','staff_users','properties','property_images','property_documents',
    'leads','activity_logs','lead_communication_logs','app_settings',
    'cms_homepage_content','cms_banners','cms_team_profiles','cms_testimonials',
    'cms_featured_properties','cms_service_showcase_items','cms_services_section',
    'cms_service_cards','team_members','market_price_statistics'
  ];
begin
  for policy_record in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public' and tablename = any(company_tables)
  loop
    execute format('drop policy %I on public.%I', policy_record.policyname, policy_record.tablename);
  end loop;
end;
$$;

-- Common current-workspace SELECT/INSERT/UPDATE rules. Activity logs are
-- deliberately handled separately below because audit records are immutable.
do $$
declare
  table_name text;
  common_tables constant text[] := array[
    'branches','staff_users','properties','property_images','property_documents',
    'leads','lead_communication_logs','app_settings',
    'cms_homepage_content','cms_banners','cms_team_profiles','cms_testimonials',
    'cms_featured_properties','cms_service_showcase_items','team_members'
  ];
begin
  foreach table_name in array common_tables loop
    if to_regclass(format('public.%I', table_name)) is not null then
      execute format('alter table public.%I enable row level security', table_name);
      execute format(
        'create policy workspace_select on public.%I for select to authenticated using (workspace_id = (select private.current_demo_workspace_id()))',
        table_name
      );
      execute format(
        'create policy workspace_insert on public.%I for insert to authenticated with check (workspace_id = (select private.current_demo_workspace_id()))',
        table_name
      );
      execute format(
        'create policy workspace_update on public.%I for update to authenticated using (workspace_id = (select private.current_demo_workspace_id())) with check (workspace_id = (select private.current_demo_workspace_id()))',
        table_name
      );
      execute format('grant select (workspace_id) on public.%I to authenticated', table_name);
    end if;
  end loop;
end;
$$;

-- Preserve the pre-workspace append-only audit model: authenticated users can
-- read and append logs only inside their selected workspace. Table privileges
-- also deny mutation even if a permissive policy is added accidentally later.
alter table public.activity_logs enable row level security;
create policy workspace_select on public.activity_logs
for select to authenticated
using (workspace_id = (select private.current_demo_workspace_id()));
create policy workspace_insert on public.activity_logs
for insert to authenticated
with check (workspace_id = (select private.current_demo_workspace_id()));
revoke update, delete on public.activity_logs from authenticated;
grant select, insert on public.activity_logs to authenticated;

-- Preserve the existing delete capability only where it already existed.
create policy workspace_delete on public.team_members
for delete to authenticated
using (workspace_id = (select private.current_demo_workspace_id()));

-- Property Services settings remain super-admin managed.
alter table public.cms_services_section enable row level security;
alter table public.cms_service_cards enable row level security;
create policy workspace_select on public.cms_services_section
for select to authenticated
using (workspace_id = (select private.current_demo_workspace_id()));
create policy workspace_insert on public.cms_services_section
for insert to authenticated
with check (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()));
create policy workspace_update on public.cms_services_section
for update to authenticated
using (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()))
with check (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()));
create policy workspace_select on public.cms_service_cards
for select to authenticated
using (workspace_id = (select private.current_demo_workspace_id()));
create policy workspace_insert on public.cms_service_cards
for insert to authenticated
with check (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()));
create policy workspace_update on public.cms_service_cards
for update to authenticated
using (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()))
with check (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()));
grant select (workspace_id) on public.cms_services_section, public.cms_service_cards to authenticated;

-- Market statistics keep published public reads and super-admin management,
-- now inside the selected workspace.
alter table public.market_price_statistics enable row level security;
create policy workspace_market_select on public.market_price_statistics
for select to authenticated
using (
  workspace_id = (select private.current_demo_workspace_id())
  and (is_published = true or (select private.is_current_workspace_super_admin()))
);
create policy workspace_market_insert on public.market_price_statistics
for insert to authenticated
with check (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()));
create policy workspace_market_update on public.market_price_statistics
for update to authenticated
using (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()))
with check (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()));
create policy workspace_market_delete on public.market_price_statistics
for delete to authenticated
using (workspace_id = (select private.current_demo_workspace_id()) and (select private.is_current_workspace_super_admin()));
grant select (workspace_id) on public.market_price_statistics to authenticated;

-- Anonymous website access remains exactly the Hilltop public/default
-- workspace. Other demo workspaces are not public in Phase 1.
create policy public_default_properties on public.properties
for select to anon
using (
  workspace_id = (select private.default_demo_workspace_id())
  and status in ('Active', 'Under Offer')
);
create policy public_default_property_images on public.property_images
for select to anon
using (
  workspace_id = (select private.default_demo_workspace_id())
  and exists (
    select 1 from public.properties property
    where property.id = property_images.property_id
      and property.workspace_id = property_images.workspace_id
      and property.status in ('Active', 'Under Offer')
  )
);
create policy public_default_branches on public.branches
for select to anon
using (workspace_id = (select private.default_demo_workspace_id()));
create policy public_default_staff_profiles on public.staff_users
for select to anon
using (
  workspace_id = (select private.default_demo_workspace_id())
  and is_active = true
  and role in ('branch_manager', 'agent')
);
create policy public_default_homepage_content on public.cms_homepage_content
for select to anon
using (workspace_id = (select private.default_demo_workspace_id()));
create policy public_default_banners on public.cms_banners
for select to anon
using (workspace_id = (select private.default_demo_workspace_id()) and is_active = true);
create policy public_default_team_profiles on public.cms_team_profiles
for select to anon
using (workspace_id = (select private.default_demo_workspace_id()) and is_visible = true);
create policy public_default_testimonials on public.cms_testimonials
for select to anon
using (workspace_id = (select private.default_demo_workspace_id()) and is_visible = true);
create policy public_default_featured_properties on public.cms_featured_properties
for select to anon
using (
  workspace_id = (select private.default_demo_workspace_id())
  and is_visible = true
  and exists (
    select 1 from public.properties property
    where property.id = cms_featured_properties.property_id
      and property.workspace_id = cms_featured_properties.workspace_id
      and property.status in ('Active', 'Under Offer')
  )
);
create policy public_default_app_settings on public.app_settings
for select to anon
using (
  workspace_id = (select private.default_demo_workspace_id())
  and setting_key in (
    'company_profile','website_preferences','seo_metadata',
    'homepage_hero_video_url','homepage_hero_poster_url','homepage_hero_video_updated_at',
    'homepage_why_hero_video_url','homepage_why_hero_poster_url','homepage_why_hero_eyebrow',
    'homepage_why_hero_title','homepage_why_card_1_title','homepage_why_card_1_short',
    'homepage_why_card_1_expanded','homepage_why_card_1_cta','homepage_why_card_2_title',
    'homepage_why_card_2_short','homepage_why_card_2_expanded','homepage_why_card_2_cta',
    'homepage_why_card_3_title','homepage_why_card_3_short','homepage_why_card_3_expanded',
    'homepage_why_card_3_cta'
  )
);
create policy public_default_service_showcase on public.cms_service_showcase_items
for select to anon
using (workspace_id = (select private.default_demo_workspace_id()) and is_active = true);
create policy public_default_team_members on public.team_members
for select to anon
using (workspace_id = (select private.default_demo_workspace_id()) and is_active = true);
create policy public_default_services_section on public.cms_services_section
for select to anon
using (
  workspace_id = (select private.default_demo_workspace_id())
  and section_key = 'homepage-property-services'
  and is_visible = true
);
create policy public_default_service_cards on public.cms_service_cards
for select to anon
using (
  workspace_id = (select private.default_demo_workspace_id())
  and is_visible = true
  and exists (
    select 1 from public.cms_services_section section
    where section.id = cms_service_cards.section_id
      and section.workspace_id = cms_service_cards.workspace_id
      and section.section_key = 'homepage-property-services'
      and section.is_visible = true
  )
);
create policy public_default_market_statistics on public.market_price_statistics
for select to anon
using (workspace_id = (select private.default_demo_workspace_id()) and is_published = true);

-- Public enquiries are automatically stamped with the default workspace by
-- the trigger and cannot target another workspace's property/branch.
create policy public_default_lead_insert on public.leads
for insert to anon
with check (
  workspace_id = (select private.default_demo_workspace_id())
  and source = 'Website'
  and status = 'New'
  and assigned_agent_id is null
  and branch_id is not null
  and length(btrim(client_name)) > 0
  and length(btrim(phone)) > 0
  and exists (
    select 1 from public.branches branch
    where branch.id = leads.branch_id
      and branch.workspace_id = leads.workspace_id
  )
  and (
    property_id is null
    or exists (
      select 1 from public.properties property
      where property.id = leads.property_id
        and property.workspace_id = leads.workspace_id
        and property.status in ('Active', 'Under Offer')
    )
  )
);

-- Security-invoker prevents the public staff view from bypassing staff RLS.
create or replace view public.public_staff_profiles
with (security_barrier = true, security_invoker = true)
as
select id, full_name, phone, role, branch_id, is_active
from public.staff_users
where workspace_id = (select private.default_demo_workspace_id())
  and is_active = true
  and role in ('branch_manager', 'agent');
grant select (id, full_name, phone, role, branch_id, is_active, workspace_id)
on public.staff_users to anon;
grant select on public.public_staff_profiles to anon;

-- Workspace-aware storage paths. New uploads use <workspace-uuid>/... . The
-- default Hilltop workspace may still access legacy unprefixed objects so the
-- migration never requires destructive object moves.
create or replace function private.try_uuid(value text)
returns uuid
language plpgsql
immutable
set search_path = ''
as $$
begin
  return value::uuid;
exception when invalid_text_representation then
  return null;
end;
$$;

create or replace function private.storage_object_in_workspace(
  object_bucket text,
  object_name text,
  workspace_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    workspace_id is not null
    and (
      (storage.foldername(object_name))[1] = workspace_id::text
      or (
        workspace_id = private.default_demo_workspace_id()
        and case
          when object_bucket in ('property-images', 'property-documents') then exists (
            select 1 from public.properties property
            where property.id = private.try_uuid((storage.foldername(object_name))[1])
              and property.workspace_id = workspace_id
          )
          else not exists (
            select 1 from public.demo_workspaces workspace
            where workspace.id = private.try_uuid((storage.foldername(object_name))[1])
          )
        end
      )
    );
$$;

revoke all on function private.try_uuid(text) from public;
revoke all on function private.storage_object_in_workspace(text, text, uuid) from public;
grant execute on function private.storage_object_in_workspace(text, text, uuid) to anon, authenticated;

do $$
declare policy_name text;
begin
  foreach policy_name in array array[
    'Workspace public media reads','Workspace authenticated media reads','Workspace authenticated media uploads',
    'Workspace authenticated media updates','Workspace managed media deletes',
    'Public can read CMS media','Authenticated users can upload CMS media','Authenticated users can update CMS media',
    'Public can read service illustrations','Super admins can upload service illustrations','Super admins can update service illustrations','Super admins can delete service illustrations',
    'Public can read team member profile images','Authenticated users can upload team member images','Authenticated users can update team member images','Authenticated users can delete team member images',
    'Public can read service showcase media','Authenticated users can upload service showcase media','Authenticated users can update service showcase media',
    'Public can read property images','Authenticated users can upload property images','Authenticated users can update property images',
    'Authenticated users can read property documents','Authenticated users can upload property documents','Authenticated users can update property documents'
  ] loop
    execute format('drop policy if exists %I on storage.objects', policy_name);
  end loop;
end;
$$;

create policy "Workspace public media reads" on storage.objects
for select to anon
using (
  bucket_id in ('property-images','cms-media','team-members','service-illustrations')
  and private.storage_object_in_workspace(bucket_id, name, private.default_demo_workspace_id())
);
create policy "Workspace authenticated media reads" on storage.objects
for select to authenticated
using (
  bucket_id in ('property-images','property-documents','cms-media','team-members','service-illustrations')
  and private.storage_object_in_workspace(bucket_id, name, private.current_demo_workspace_id())
);
create policy "Workspace authenticated media uploads" on storage.objects
for insert to authenticated
with check (
  bucket_id in ('property-images','property-documents','cms-media','team-members','service-illustrations')
  and (storage.foldername(name))[1] = private.current_demo_workspace_id()::text
  and (bucket_id <> 'service-illustrations' or (select private.is_current_workspace_super_admin()))
);
create policy "Workspace authenticated media updates" on storage.objects
for update to authenticated
using (
  bucket_id in ('property-images','property-documents','cms-media','team-members','service-illustrations')
  and private.storage_object_in_workspace(bucket_id, name, private.current_demo_workspace_id())
  and (bucket_id <> 'service-illustrations' or (select private.is_current_workspace_super_admin()))
)
with check (
  bucket_id in ('property-images','property-documents','cms-media','team-members','service-illustrations')
  and (storage.foldername(name))[1] = private.current_demo_workspace_id()::text
  and (bucket_id <> 'service-illustrations' or (select private.is_current_workspace_super_admin()))
);
create policy "Workspace managed media deletes" on storage.objects
for delete to authenticated
using (
  bucket_id in ('team-members','service-illustrations')
  and private.storage_object_in_workspace(bucket_id, name, private.current_demo_workspace_id())
  and (bucket_id <> 'service-illustrations' or (select private.is_current_workspace_super_admin()))
);

-- New indexes match the dominant tenant + status/order filters.
create index if not exists idx_properties_workspace_status_created
  on public.properties (workspace_id, status, created_at desc);
create index if not exists idx_leads_workspace_status_created
  on public.leads (workspace_id, status, created_at desc);
create index if not exists idx_staff_users_workspace_active
  on public.staff_users (workspace_id, is_active);
create index if not exists idx_branches_workspace_name
  on public.branches (workspace_id, name);
create index if not exists idx_activity_logs_workspace_created
  on public.activity_logs (workspace_id, created_at desc);
create index if not exists idx_app_settings_workspace_category
  on public.app_settings (workspace_id, setting_category);

comment on table public.demo_workspaces is
'Company/demo tenant boundary. Phase 1 stores identity and lifecycle only; branding and domain fields belong to a later phase.';
comment on column public.demo_workspaces.is_public_default is
'Pins the unchanged Phase 1 public website to the migrated Hilltop template workspace.';

commit;
